// <auto-generated />
using System;
using Lab08_Parking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab08_Parking.Data.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20201219114525_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Lab08_Parking.Data.Models.DiscountCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<byte>("Discount")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParkingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParkingId");

                    b.ToTable("DiscountCards");
                });

            modelBuilder.Entity("Lab08_Parking.Data.Models.Parking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DailyRateStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DailyRateStopTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NightlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("Size")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("Lab08_Parking.Data.Models.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("DiscountCardId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParkingId")
                        .HasColumnType("bigint");

                    b.Property<string>("RegNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Size")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("DiscountCardId");

                    b.HasIndex("ParkingId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Lab08_Parking.Data.Models.DiscountCard", b =>
                {
                    b.HasOne("Lab08_Parking.Data.Models.Parking", "Parking")
                        .WithMany("DiscountCards")
                        .HasForeignKey("ParkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("Lab08_Parking.Data.Models.Vehicle", b =>
                {
                    b.HasOne("Lab08_Parking.Data.Models.DiscountCard", "DiscountCard")
                        .WithMany("Vehicles")
                        .HasForeignKey("DiscountCardId");

                    b.HasOne("Lab08_Parking.Data.Models.Parking", "Parking")
                        .WithMany("Vehicles")
                        .HasForeignKey("ParkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscountCard");

                    b.Navigation("Parking");
                });

            modelBuilder.Entity("Lab08_Parking.Data.Models.DiscountCard", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Lab08_Parking.Data.Models.Parking", b =>
                {
                    b.Navigation("DiscountCards");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
